### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by amithdodangoda** [YuejiangLIU/social-nce-trajectron-plus-plus#1]
Could you please guide me to the inference code?

**Comment by YuejiangLIU** [comment]
Here's the function for inference (same as the vanilla Trajectron++)
https://github.com/YuejiangLIU/social-nce-trajectron-plus-plus/blob/5840f69d6c5009f0fa10d11ee8c0f401763b1840/trajectron/model/trajectron.py#L139

**Comment by YuejiangLIU** [comment]
I'm closing it for now. Please feel free to reopen it if you have further questions.
