### ISSUE TITLE
Is there an implementation with social-LSTM?

### ISSUE THREAD

**Issue by TimHo0331** [YuejiangLIU/social-nce-trajectron-plus-plus#3]
Dear authors,
  In the paper, the social-nce loss is also applied to the Social-LSTM model.
  Will this code going to be released?
  The implementations of trajectron++ and stgcnn are relatively complex.
  It is better to see how the social-nce loss works on simple model.

Thanks!

**Comment by YuejiangLIU** [comment]
Our implementation of the social-nce loss applied to Social-LSTM is pretty similar to that applied to [trajectron++](https://github.com/YuejiangLIU/social-nce-trajectron-plus-plus/tree/master/trajectron/snce) and [crowdnav](https://github.com/vita-epfl/social-nce/tree/main/crowd_nav/snce). We'll be glad to release it, once our model falls off the Trajnet++ leaderboard.

**Comment by TimHo0331** [comment]
> Our implementation of the social-nce loss applied to Social-LSTM is pretty similar to that applied to [trajectron++](https://github.com/YuejiangLIU/social-nce-trajectron-plus-plus/tree/master/trajectron/snce) and [crowdnav](https://github.com/vita-epfl/social-nce/tree/main/crowd_nav/snce). We'll be glad to release it, once our model falls off the Trajnet++ leaderboard.

Thank you for your reply! 
Is it possible to release an implementation of social-nce loss applied to a simple model? For example, a very simple LSTM or MLP network without interaction modelling.
In trajectron++, the code is based on a CVAE-based model output, which is kind of complex to understand the meaning of different variables...

**Comment by YuejiangLIU** [comment]
The policy network for imitation learning in the CrowdNav task is fairly light-weighted. The network has a simple encoder and interaction model. Here's the [code](https://github.com/vita-epfl/social-nce/blob/main/crowd_nav/policy/sail.py).

**Comment by TimHo0331** [comment]
May I ask a question about the implementation of social-nce applied to trajectron++?
In [https://github.com/YuejiangLIU/social-nce-trajectron-plus-plus/blob/fb36669c52af964a8afa58304b9b407e394a3105/trajectron/snce/contrastive.py#L76](url), the shape of variable sim_pos is (batch_size, num_samples, 3), what is the meaning of samples here? Sample 25 latent variables from the latent space?
And why average the positive samples, but not the negative samples?

**Comment by TimHo0331** [comment]
Another question is, Is the temporal embedding (time_pos & time_neg) necessary? This seems not described in the paper.

**Comment by YuejiangLIU** [comment]
> 

As far as I remember, the Trajectron++ samples 25 latent codes for predictions. These latent codes should all stay away from negative samples. However, given the uncertainty of the future, they do not have to all hit the positive sample. We, therefore, take the average.

**Comment by YuejiangLIU** [comment]
> May I ask a question about the implementation of social-nce applied to trajectron++? In [https://github.com/YuejiangLIU/social-nce-trajectron-plus-plus/blob/fb36669c52af964a8afa58304b9b407e394a3105/trajectron/snce/contrastive.py#L76](url), the shape of variable sim_pos is (batch_size, num_samples, 3), what is the meaning of samples here? Sample 25 latent variables from the latent space? And why average the positive samples, but not the negative samples?


As far as I remember, the Trajectron++ samples 25 latent codes for predictions. These latent codes should all stay away from negative samples. However, given the uncertainty of the future, they do not have to all hit the positive sample. We, therefore, take the average.

**Comment by YuejiangLIU** [comment]
> Another question is, Is the temporal embedding (time_pos & time_neg) necessary? This seems not described in the paper.

The <state, time> forms the event described in our paper. The method was still effective when we dropped the time part, i.e., only draw samples at a fixed time step. But sampling the future events from a temporal window led to better results in our previous experiments.
